### ISSUE TITLE
Condensed Formula

### ISSUE THREAD

**Issue by rfellers** [rfellers/chemForma#2]
From #1 

## Condensed formula
Chemists often describe molecules in condensed form. For example, hexane can be written as CH<sub>3</sub>(CH<sub>2</sub>)<sub>4</sub>CH<sub>3</sub>. If parentheses are reserved for indicating isotopes, maybe that could be represented as `CH3[CH2]4CH3`. I think that improves human readability but only a little.

**Comment by rfellers** [comment]
@bdrown I think this should be a first class requirement and I should change how isotopes are handled. To best match the common case, I think your example above should be:

`CH3(CH2)4CH3`

To handle isotopes, I'd use your braces:

`[13]CH3([13]CH2)4[13]CH3`

Thoughts?

**Comment by bdrown** [comment]
Yeah, I prefer using braces for denoting isotope and parentheses for grouping repeating units.
